[workspace]
members = [
  "crates/types",
  "crates/replication",
  "crates/wal",
  "crates/txn",
  "crates/execution",
  "crates/engine",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
