[workspace]
members = [
  "crates/types",
  "crates/sql",
  "crates/replication",
  "crates/wal",
  "crates/txn",
  "crates/execution",
  "crates/planner",
  "crates/batching",
  "crates/metrics",
  "crates/observability",
  "crates/protocol",
  "crates/storage",
  "crates/write_conveyor",
  "crates/engine",
  "crates/facade",
  "crates/server",
  "crates/snapshot",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive", "rc"] }
libloading = "0.8"
imbl = "7"
arc-swap = "1"
tikv-jemallocator = "0.6"
