\echo === bounded default table privileges ===
CREATE TABLE default_acl_existing (id INT, name TEXT);
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT ON TABLES TO PUBLIC;
\ddp
CREATE TABLE default_acl_first (id INT, name TEXT);
\dp default_acl_existing
\dp default_acl_first
ALTER DEFAULT PRIVILEGES REVOKE INSERT ON TABLES FROM PUBLIC;
\ddp
CREATE TABLE default_acl_second (id INT, name TEXT);
\dp default_acl_second
ALTER DEFAULT PRIVILEGES GRANT ALL PRIVILEGES ON TABLES TO postgres;
\ddp
CREATE TABLE default_acl_third (id INT, name TEXT);
\z public.default_acl_*
ALTER DEFAULT PRIVILEGES REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL PRIVILEGES ON TABLES FROM postgres;
\ddp
CREATE TABLE default_acl_fourth (id INT, name TEXT);
\dp default_acl_fourth
ALTER DEFAULT PRIVILEGES IN SCHEMA private GRANT SELECT ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO missing_role;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO PUBLIC WITH GRANT OPTION;
SELECT name FROM default_acl_first WHERE id = 1;
