\pset pager off
\echo === bounded relation ACL enforcement ===
CREATE ROLE acl_reader;
CREATE ROLE acl_writer;
CREATE TABLE acl_people (id INT, name TEXT);
INSERT INTO acl_people (id, name) VALUES (1, 'ada'), (2, 'grace');
SET ROLE acl_reader;
SELECT id, name FROM acl_people ORDER BY id;
INSERT INTO acl_people (id, name) VALUES (3, 'denied');
RESET ROLE;
GRANT SELECT ON TABLE acl_people TO acl_reader;
SET ROLE acl_reader;
SELECT id, name FROM acl_people ORDER BY id;
UPDATE acl_people SET name = 'denied' WHERE id = 1;
RESET ROLE;
GRANT INSERT, UPDATE, DELETE ON TABLE acl_people TO acl_writer;
SET ROLE acl_writer;
INSERT INTO acl_people (id, name) VALUES (3, 'katherine');
UPDATE acl_people SET name = 'lovelace' WHERE id = 1;
DELETE FROM acl_people WHERE id = 2;
SET ROLE DEFAULT;
SELECT id, name FROM acl_people ORDER BY id;
\echo === default ACL and role rename ===
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO acl_reader;
CREATE TABLE acl_defaulted (id INT, name TEXT);
INSERT INTO acl_defaulted (id, name) VALUES (7, 'default grant');
ALTER ROLE acl_reader RENAME TO acl_analyst;
SET ROLE acl_analyst;
SELECT id, name FROM acl_defaulted ORDER BY id;
INSERT INTO acl_defaulted (id, name) VALUES (8, 'denied');
RESET ROLE;
\echo === view and materialized view ACL enforcement ===
CREATE VIEW acl_people_view AS SELECT id, name FROM acl_people ORDER BY id;
CREATE MATERIALIZED VIEW acl_people_mv AS SELECT id, name FROM acl_people ORDER BY id;
SET ROLE acl_analyst;
SELECT * FROM acl_people_view;
SELECT * FROM acl_people_mv;
RESET ROLE;
GRANT SELECT ON VIEW acl_people_view TO acl_analyst;
GRANT SELECT ON MATERIALIZED VIEW acl_people_mv TO PUBLIC;
SET ROLE acl_analyst;
SELECT * FROM acl_people_view;
SELECT * FROM acl_people_mv;
RESET ROLE;
REVOKE SELECT ON TABLE acl_defaulted FROM acl_analyst;
SET ROLE acl_analyst;
SELECT id, name FROM acl_defaulted ORDER BY id;
RESET ROLE;
SET ROLE missing_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM acl_analyst;
REVOKE SELECT ON TABLE acl_people FROM acl_analyst;
REVOKE INSERT, UPDATE, DELETE ON TABLE acl_people FROM acl_writer;
REVOKE SELECT ON VIEW acl_people_view FROM acl_analyst;
REVOKE SELECT ON MATERIALIZED VIEW acl_people_mv FROM PUBLIC;
DROP MATERIALIZED VIEW acl_people_mv;
DROP VIEW acl_people_view;
DROP TABLE acl_defaulted;
DROP TABLE acl_people;
DROP ROLE acl_analyst, acl_writer;
