\pset pager off
\echo === bounded schema CREATE ACL enforcement ===
CREATE ROLE schema_builder;
CREATE TABLE schema_acl_source (id INT, name TEXT);
INSERT INTO schema_acl_source (id, name) VALUES (1, 'ada'), (2, 'grace');
GRANT SELECT ON TABLE schema_acl_source TO schema_builder;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SET ROLE schema_builder;
CREATE TABLE schema_denied_table (id INT);
CREATE SEQUENCE schema_denied_seq;
CREATE FUNCTION schema_denied_fn() RETURNS int4 LANGUAGE sql AS 'SELECT 1';
CREATE DOMAIN schema_denied_domain AS int4;
CREATE VIEW schema_denied_view AS SELECT id, name FROM schema_acl_source ORDER BY id;
CREATE MATERIALIZED VIEW schema_denied_mv AS SELECT id, name FROM schema_acl_source ORDER BY id;
CREATE PUBLICATION schema_denied_pub FOR TABLE schema_acl_source;
CREATE SUBSCRIPTION schema_denied_sub CONNECTION 'host=localhost' PUBLICATION schema_denied_pub WITH (connect = false, enabled = false);
RESET ROLE;
GRANT USAGE, CREATE ON SCHEMA public TO schema_builder;
SET ROLE schema_builder;
CREATE TABLE schema_allowed_table (id INT, name TEXT);
CREATE INDEX schema_allowed_idx ON schema_allowed_table (id);
CREATE SEQUENCE schema_allowed_seq;
CREATE FUNCTION schema_allowed_fn() RETURNS int4 LANGUAGE sql AS 'SELECT 42';
CREATE DOMAIN schema_allowed_domain AS int4;
CREATE VIEW schema_allowed_view AS SELECT id, name FROM schema_acl_source ORDER BY id;
CREATE MATERIALIZED VIEW schema_allowed_mv AS SELECT id, name FROM schema_acl_source ORDER BY id;
CREATE PUBLICATION schema_allowed_pub FOR TABLE schema_acl_source;
CREATE SUBSCRIPTION schema_allowed_sub CONNECTION 'host=localhost' PUBLICATION schema_allowed_pub WITH (connect = false, enabled = false);
RESET ROLE;
\dt schema_allowed*
SELECT schema_allowed_fn();
SELECT * FROM schema_allowed_view;
SELECT * FROM schema_allowed_mv;
SELECT nextval('schema_allowed_seq');
REVOKE CREATE ON SCHEMA public FROM schema_builder;
GRANT CREATE ON SCHEMA public TO PUBLIC;
SET ROLE schema_builder;
CREATE TABLE schema_public_allowed (id INT);
RESET ROLE;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER ROLE schema_builder RENAME TO schema_creator;
GRANT USAGE, CREATE ON SCHEMA public TO schema_creator;
SET ROLE schema_creator;
CREATE SEQUENCE schema_renamed_allowed_seq;
RESET ROLE;
REVOKE USAGE, CREATE ON SCHEMA public FROM schema_creator;
SET ROLE schema_creator;
CREATE TABLE schema_denied_after_revoke (id INT);
RESET ROLE;
SELECT nextval('schema_renamed_allowed_seq');
DROP SUBSCRIPTION schema_allowed_sub;
DROP PUBLICATION schema_allowed_pub;
DROP MATERIALIZED VIEW schema_allowed_mv;
DROP VIEW schema_allowed_view;
REVOKE SELECT ON TABLE schema_acl_source FROM schema_creator;
DROP TABLE schema_public_allowed;
DROP TABLE schema_allowed_table;
DROP SEQUENCE schema_allowed_seq;
DROP SEQUENCE schema_renamed_allowed_seq;
DROP FUNCTION schema_allowed_fn();
DROP DOMAIN schema_allowed_domain;
DROP TABLE schema_acl_source;
DROP ROLE schema_creator;
