\pset pager off
\echo === bounded schema USAGE ACL enforcement ===
CREATE ROLE acl_usage;
CREATE TABLE acl_usage_people (id INT, name TEXT);
INSERT INTO acl_usage_people (id, name) VALUES (1, 'ada'), (2, 'grace');
CREATE SEQUENCE acl_usage_seq;
CREATE FUNCTION acl_usage_answer() RETURNS int4 LANGUAGE sql AS 'SELECT 42';
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE acl_usage_people TO acl_usage;
GRANT UPDATE ON SEQUENCE acl_usage_seq TO acl_usage;
GRANT CREATE ON SCHEMA public TO acl_usage;
SET ROLE acl_usage;
SELECT id, name FROM acl_usage_people ORDER BY id;
INSERT INTO acl_usage_people (id, name) VALUES (3, 'denied');
SELECT nextval('acl_usage_seq');
SELECT acl_usage_answer();
RESET ROLE;
GRANT USAGE ON SCHEMA public TO acl_usage;
SET ROLE acl_usage;
SELECT id, name FROM acl_usage_people ORDER BY id;
INSERT INTO acl_usage_people (id, name) VALUES (3, 'katherine');
UPDATE acl_usage_people SET name = 'lovelace' WHERE id = 1;
DELETE FROM acl_usage_people WHERE id = 2;
SELECT id, name FROM acl_usage_people ORDER BY id;
SELECT nextval('acl_usage_seq');
SELECT currval('acl_usage_seq');
RESET ROLE;
GRANT SELECT ON SEQUENCE acl_usage_seq TO acl_usage;
SET ROLE acl_usage;
SELECT currval('acl_usage_seq');
RESET ROLE;
REVOKE UPDATE ON SEQUENCE acl_usage_seq FROM acl_usage;
SET ROLE acl_usage;
SELECT setval('acl_usage_seq', 10);
RESET ROLE;
GRANT UPDATE ON SEQUENCE acl_usage_seq TO acl_usage;
GRANT EXECUTE ON FUNCTION acl_usage_answer() TO acl_usage;
SET ROLE acl_usage;
SELECT setval('acl_usage_seq', 10);
SELECT acl_usage_answer();
RESET ROLE;
REVOKE USAGE ON SCHEMA public FROM acl_usage;
SET ROLE acl_usage;
SELECT id, name FROM acl_usage_people ORDER BY id;
SELECT nextval('acl_usage_seq');
SELECT acl_usage_answer();
RESET ROLE;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE acl_usage_people FROM acl_usage;
REVOKE SELECT, UPDATE ON SEQUENCE acl_usage_seq FROM acl_usage;
REVOKE EXECUTE ON FUNCTION acl_usage_answer() FROM acl_usage;
REVOKE CREATE ON SCHEMA public FROM acl_usage;
DROP FUNCTION acl_usage_answer();
DROP SEQUENCE acl_usage_seq;
DROP TABLE acl_usage_people;
DROP ROLE acl_usage;
