CREATE ROLE func_reader;
CREATE FUNCTION acl_answer() RETURNS int LANGUAGE sql AS 'SELECT 42';
GRANT USAGE ON SCHEMA public TO func_reader;
SET ROLE func_reader;
SELECT acl_answer();
RESET ROLE;
GRANT EXECUTE ON FUNCTION public.acl_answer() TO func_reader;
\df+ acl_answer
SET ROLE func_reader;
SELECT acl_answer();
RESET ROLE;
ALTER ROLE func_reader RENAME TO func_executor;
SET ROLE func_executor;
SELECT acl_answer();
RESET ROLE;
REVOKE EXECUTE ON FUNCTION acl_answer() FROM func_executor;
SET ROLE func_executor;
SELECT acl_answer();
RESET ROLE;
GRANT EXECUTE ON FUNCTION acl_answer() TO PUBLIC;
SET ROLE func_executor;
SELECT acl_answer();
RESET ROLE;
REVOKE ALL PRIVILEGES ON FUNCTION acl_answer() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION acl_answer(int4) TO PUBLIC;
GRANT EXECUTE ON FUNCTION missing_answer() TO PUBLIC;
REVOKE USAGE ON SCHEMA public FROM func_executor;
DROP ROLE func_executor;
DROP FUNCTION acl_answer();
